### ISSUE TITLE
Undetected Key Conflict Error

### ISSUE THREAD

**Issue by rennsax** [emancu/toml-rb#149]
The following TOML input should be invalid:

```toml
[[foo]]
a = true

[foo]
b = false
```

But toml-rb parses it and returns `{"foo"=>[{"a"=>true, "b"=>false}]}`.
