### ISSUE TITLE
Unable to parse valid pyproject.toml configuration

### ISSUE THREAD

**Issue by ukalwa** [emancu/toml-rb#155]
Hi,

Dependabot (which depends on toml-rb for pyproject.toml parsing) is failing on a valid pyproject.toml file. Here is a simple reproducible MRE

pyproject.toml:
```toml
[tool.ruff]
target-version = "py310"

line-length = 88
exclude = [ ".git", ".mypy_cache", ".pytest_cache", ".venv", "__pycache__" ]
lint.select = [
  # flake8-bugbear
  "B",
  # flake8-comprehensions
  "C4",
  # pycodestyle
  "E",
  # pyflakes
  "F",
  # Fastapi
  "FAST",
  # isort
  "I",
  # pep8-naming
  "N",
  # Meta rules
  "RUF",
  # flake8-print
  "T20",
  # pyupgrade
  "UP",
  "W",
]
lint.ignore = [ "B008", "C901", "RUF012", "RUF029", "UP007" ]
lint.exclude = [ "*.ipynb" ]
lint.per-file-ignores = { "__init__.py" = [
  "F401",
], "migrations/versions/*.py" = [
  "E501",
  "W291",
] }
lint.preview = true
```

parse_toml.rb:
```ruby
require 'toml-rb'
TOMLRB.load_file("pyproject.toml")
```

Test:
```shell
gem install toml-rb
ruby parse_toml.rb 
# Should succeed but fails with /var/lib/gems/3.1.0/gems/toml-rb-4.0.0/lib/toml-rb/keyvalue.rb:21:in `block in assign': Key "lint" is defined more than once (TomlRB::ValueOverwriteError)
        from /var/lib/gems/3.1.0/gems/toml-rb-4.0.0/lib/toml-rb/keyvalue.rb:21:in `merge!'
        from /var/lib/gems/3.1.0/gems/toml-rb-4.0.0/lib/toml-rb/keyvalue.rb:21:in `assign'
        from /var/lib/gems/3.1.0/gems/toml-rb-4.0.0/lib/toml-rb/parser.rb:36:in `visit_keyvalue'
        from /var/lib/gems/3.1.0/gems/toml-rb-4.0.0/lib/toml-rb/keyvalue.rb:40:in `accept_visitor'
        from /var/lib/gems/3.1.0/gems/toml-rb-4.0.0/lib/toml-rb/parser.rb:14:in `block in initialize'
        from /var/lib/gems/3.1.0/gems/toml-rb-4.0.0/lib/toml-rb/parser.rb:14:in `each'
        from /var/lib/gems/3.1.0/gems/toml-rb-4.0.0/lib/toml-rb/parser.rb:14:in `initialize'
        from /var/lib/gems/3.1.0/gems/toml-rb-4.0.0/lib/toml-rb.rb:46:in `new'
        from /var/lib/gems/3.1.0/gems/toml-rb-4.0.0/lib/toml-rb.rb:46:in `parse'
        from /var/lib/gems/3.1.0/gems/toml-rb-4.0.0/lib/toml-rb.rb:70:in `load_file'
```
