### ISSUE TITLE
Unable to parse nested array of tables

### ISSUE THREAD

**Issue by lessless** [emancu/toml-rb#24]
This example is from the toml github page 

```ruby
[[fruit]]
  name = "apple"

  [fruit.physical]
    color = "red"
    shape = "round"

  [[fruit.variety]]
    name = "red delicious"

  [[fruit.variety]]
    name = "granny smith"

[[fruit]]
  name = "banana"

  [[fruit.variety]]
    name = "plantain"

```
this is the exactly same data type on which toml-rb is crashing in my case. here is the error for the snippet: 

```ruby
/home/lessless/.rvm/gems/ruby-2.0.0-p247/gems/citrus-2.4.1/lib/citrus.rb:636:in `parse': Failed to parse input on line 1 at offset 1 (Citrus::ParseError)
[[fruit]]

 ^
	from /home/lessless/.rvm/gems/ruby-2.0.0-p247/gems/citrus-2.4.1/lib/citrus.rb:374:in `parse'
	from /home/lessless/.rvm/gems/ruby-2.0.0-p247/gems/toml-rb-0.1.3/lib/toml/parser.rb:10:in `initialize'
	from /home/lessless/.rvm/gems/ruby-2.0.0-p247/gems/toml-rb-0.1.3/lib/toml.rb:30:in `new'
	from /home/lessless/.rvm/gems/ruby-2.0.0-p247/gems/toml-rb-0.1.3/lib/toml.rb:30:in `parse'
	from 1.rb:25:in `<main>'

```

**Comment by bararchy** [comment]
Is this feature implemented yet ? this looks like something I may need in my next project

**Comment by emancu** [comment]
@bararchy I'm sorry I didn't update the gem.
But, next week I'll have some free time, so I can work on this issue.

**Comment by emancu** [comment]
@bararchy I'm sorry I didn't give you any update. It was a mess.
Today I'm back working on `toml-rb` supporting the new specification (0.3.0) so I'll keep you posted.

**Comment by bararchy** [comment]
@emancu , No worries :+1:  Thanks for the update

**Comment by emancu** [comment]
Here is the specs for 0.3.1

Array of Tables
---------------

The last type that has not yet been expressed is an array of tables. These can
be expressed by using a table name in double brackets. Each table with the same
double bracketed name will be an element in the array. The tables are inserted
in the order encountered. A double bracketed table without any key/value pairs
will be considered an empty table.

```toml
[[products]]
name = "Hammer"
sku = 738594937

[[products]]

[[products]]
name = "Nail"
sku = 284758393
color = "gray"
```

In JSON land, that would give you the following structure.

```json
{
  "products": [
    { "name": "Hammer", "sku": 738594937 },
    { },
    { "name": "Nail", "sku": 284758393, "color": "gray" }
  ]
}
```

You can create nested arrays of tables as well. Just use the same double bracket
syntax on sub-tables. Each double-bracketed sub-table will belong to the most
recently defined table element above it.

```toml
[[fruit]]
  name = "apple"

  [fruit.physical]
    color = "red"
    shape = "round"

  [[fruit.variety]]
    name = "red delicious"

  [[fruit.variety]]
    name = "granny smith"

[[fruit]]
  name = "banana"

  [[fruit.variety]]
    name = "plantain"
```

The above TOML maps to the following JSON.

```json
{
  "fruit": [
    {
      "name": "apple",
      "physical": {
        "color": "red",
        "shape": "round"
      },
      "variety": [
        { "name": "red delicious" },
        { "name": "granny smith" }
      ]
    },
    {
      "name": "banana",
      "variety": [
        { "name": "plantain" }
      ]
    }
  ]
}
```

Attempting to define a normal table with the same name as an already established
array must produce an error at parse time.

```toml
# INVALID TOML DOC
[[fruit]]
  name = "apple"

  [[fruit.variety]]
    name = "red delicious"

  # This table conflicts with the previous table
  [fruit.variety]
    name = "granny smith"
```
