### ISSUE TITLE
Support literal strings

### ISSUE THREAD

**Issue by rsim** [emancu/toml-rb#28]
From TOML 0.3.1 specification:

TOML supports literal strings where there is no escaping allowed at all. Literal strings are surrounded by single quotes. Like basic strings, they must appear on a single line:
```toml
# What you see is what you get.
winpath  = 'C:\Users\nodejs\templates'
winpath2 = '\\ServerX\admin$\system32\'
quoted   = 'Tom "Dubs" Preston-Werner'
regex    = '<\i\c*\s*>'
```
