### ISSUE TITLE
TOML dump should quote non-bare keys

### ISSUE THREAD

**Issue by rsim** [emancu/toml-rb#32]
Bare keys should be dumped unquoted (as currently) but non-bare keys should be quoted in TOML dump.
```ruby
TOML.dump "key"=>"value","bare_key"=>"value","bare-key"=>"value","quoted.key"=>"value",
  "quoted.table"=>{"key"=>"value"}
```
should produce
```toml
key = "value"
bare_key = "value"
bare-key = "value"
"quoted.key" = "value"
["quoted.table"]
key = "value"
```
